# Generated by Django 4.0 on 2021-12-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_img', models.ImageField(upload_to='static/main/img/img')),
            ],
        ),
    ]
