# Generated by Django 4.0 on 2021-12-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_gallery_delete_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='gallery_img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
